// <auto-generated />
namespace EPS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20150929addtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150929addtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201509290525464_20150929-addtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
